//
//  DataManager.swift
//  SMPCards
//
//  Created by Максим Жуков on 16.11.2020.
//  Copyright © 2020 Максим Жуков. All rights reserved.
//

import Foundation

extension String: ResponseSubAttribute {}
extension Array: ResponseSubAttribute {}

protocol ResponseSubAttribute {}

enum  RequestOfSubattributeData {
    case title
    case frame
}

struct FrameOfSubAttribute {
    let x: Double
    let y: Double
    let weight: Double
    let height: Double
    let paragraphLenght: Int
    let lineSpacing: Double
    let isMain: Bool
}

class DataCollections {
        
    static let titles: [SubAttribute: String] = [
        .numberOfCard : "Номер карты", .name : "Имя", .Complaints: "Жалобы", .gotSickBeforeAnHour: "до часа", .gotSick1_3Hours: "от 1 до 3 часов", .gotSick3_6Hours: "от 3 до 6 часов", .gotSick6_12Hours: "от 6 до 12 часов", .gotSickMoreADay: "свыше суток", .conditionIsSatisfactory: "удовлетворительное", .conditionIsOfModerateSeverity: "средней тяжести", .conditionIsHeavy: "тяжелое", .conditionIsTerminal: "терминальное", .conditionIsDeath: "смерть", .consciousnessIsClear: "ясное", .consciousnessIsStunning: "оглушение", .consciousnessIsSopor: "сопор", .consciousnessIsComa1: "кома 1 ст.", .consciousnessIsComa2: "кома 2 ст.", .consciousnessIsComa3: "кома 3 ст.", .positionIsActive: "активное", .positionIsPassive: "пассивное", .positionIsForced: "вынуженное", .skinIsDry: "сухие", .skinIsWet: "влажные", .skinIsWarm: "теплые", .skinIsCold: "холодные", .skinIsPhisiologicalColor: "физиологической окраски", .skinIsPale: "бледные", .skinIsHyperemic: "гипермированные", .skinIsCyanotic: "цианотичные", .skinIsJaundice: "желтушные", .skinIsAcrocyanosis: "акроцианоз", .skinIsMarbling: "мраморность", .hasRash: "нет", .hasNotRash: "есть", .hasEdema: "есть", .hasNotEdema: "нет", .behaviorIsCalm: "спокойное", .behaviorIsAgitated: "возбужденное", .behaviorIsAggressive: "агрессивное", .behaviorIsDepressive: "депрессивное", .behaviorIsKontacten: "контактен", .behaviorIsNotKontacten: "не контактен", .behaviorIsAmnesia: "амнезия", .behaviorIsataxia: "атаксия", .pupilsIsODIsEqualOS: "OD = OS", .pupilsIsODIsNotEqualOS: "OD != OS", .pupilsIsNormal: "обычные", .pupilsIsWide: "широкие", .pupilsIsNarrow: "узкие", .pupilsIsAnisocoria: "анизокория", .reactionToLightIsAlive: "живая", .reactionToLightIsHoly: "вялая", .reactionToLightIsNone: "отсутствует", .hasNystagm: "есть", .hasNotNystagm: "нет", .regedivnostZatilochnihMuscle: "ригидивность затылочных мышц", .kernig: "Кернига", .brudzinski: "Брудзинского", .hasNotMeningealSymptom: "нет", .hasFocalSymptoms: "есть", .hasNotFocalSymptoms: "нет", .breathFeel: "свободное", .breathNotFeel: "затруднено", .hasSeparatedFromNasalPassages: "есть", .hasNotSeparatedFromNasalPassages: "нет", .dyspneaIsInspiratory: "инспираторная", .dyspneaIsExpiratory: "экспираторная", .dyspneaIsmixed: "смешенная", .dyspneaIsPotalogic: "патологическое дыхание", .percussionSoundIsPulmonary: "легочный", .percussionSoundIsShortened: "укорочен", .percussionSoundIsTympanic: "тимпанический", .percussionSoundIsDull: "тупой", .percussionSoundIsBoxboardAbove: "коробочный над", .auscultationBreathIsPuerile: "пуэрильное", .auscultationBreathIsVesicular: "везикулярное", .auscultationBreathIsBronchial: "бронхиальное", .auscultationBreathIsHard: "жесткое", .auscultationBreathIsTenatic: "cтенотическое", .auscultationBreathIsWeakened:  "ослаблено", .auscultationBreathNone: "отсутствует", .hasNotRale: "нет", .dryRale: "сухие", .wetRaleSmallbubble: "влажные-мелкопузырчатые", .wetRaleMediumbubble: "влажные-среднепузырчатые", .wetRaleLargebubble: "влажные-крупнопузырчатые", .hasPleuralFrictionNoise: "нет", .hasNotPleuralFrictionNoise: "есть", .heartTonesIsResonant: "звучные", .heartTonesIsPriglasheny: "приглушены", .heartTonesIsDeaf: "глухие", .noiseIsSystolic: "систолический", .noiseIsDiastolic: "диастолический", .noiseIsAccent: "акцент", .hasNoiseOfFrictionPericard: "есть", .hasNotNoiseOfFrictionPericard: "нет", .tongueIsWet: "влажный", .tongueIsDry: "сухой", .tongueIsOverlaid: "обложен", .stomachIsSoft: "мягкий", .stomachIsTense: "напряжен", .stomachIsPainful: "болезненный", .stomachIsNotPainful: "безболезненный во всех отделах", .positiveSymptomOfSidkovskogo: "Ситковского", .positiveSymptomRovsinga: "Ровзинга", .positiveSymptomMerphy: "Мерфи", .positiveSymptomOfOrtner: "Ортнера", .positiveSymptomOfMayoRobson: "Мейо-Робсона", .positiveSymptomOfObraztsov: "Образцова", .positiveSymptomOfRazdolsky: "Раздольского", .positiveSymptomOfShchetkinBlumberg: "Щеткина-Блюмберга", .positiveSymptomOfValya: "Валя", .positiveSymptomOfSklyarov: "Склярова", .positiveSymptomOfGrekov: "Грекова", .positiveSymptomOfRozanov: "Розанова", .positiveSymptomOfSpijarski: "Спижарского", .dyspepsiaNausea: "тошнота", .dyspepsiaVomiting: "рвота", .chairIsFormed: "оформленный", .chairIsZapor: "запор", .chairIsLiquid: "жидкий", .diuresisIsSufficient: "достаточный", .diuresisIsreduced: "снижен", .diuresisIspolyuria: "полиурия", .diuresisIshematuria: "гематурия", .diuresisIsAnuria: "анурия", .adBeforeMedHelp: "АД до тепрапии:", .adAfterMedHelp: "АД после тепрапии:", .chssBeforeMedHelp: "ЧСС до тепрапии:", .chssAfterMedHelp: "ЧСС после тепрапии:", .pBeforeMedHelp:  "P до тепрапии:", .pAfterMedHelp: "P после тепрапии:", .chddBeforeMedHelp: "ЧДД до тепрапии:", .chddAfterMedHelp: "ЧДД после тепрапии:", .tBeforeMedHelp:  "T°C до тепрапии:", .tAfterMedHelp: "T°C после тепрапии:", .spOBeforeMedHelp: "Сатурация до тепрапии:", .spOAfterMedHelp: "Сатурация после тепрапии", .glukozaBeforeMedHelp: "Глюкоза до тепрапии:", .glukozaAfterMedHelp: "Глюкоза после тепрапии:", .resuscitation: "Реанимация", .ivl_vvl: "ИВЛ/ВВЛ", .nebulizer: "Небулайзер", .intubationAndlaryngitis: "Интубация/ларинг", .conicotomy: "Коникотомия", .trachestomy: "Трахеотомия", .eit: "ЭИТ", .thrombolysis: "Тромболизис", .catheterMoch: "Катетер. мочев.", .pills: "Таблетки", .rinsingStomach: "Промыв. желудка", .pulseoximetry: "Пульсоксиметрия", .infusion: "Инфузия", .catheterVV: "Катетер в/в", .ostBlodRan: "Ост. кров/обр. ран", .bandage: "Повязка/п/ожог", .immobilization: "Иммобилизация", .defibrillation: "Дефибрилляция", .nasalTamponade: "Тампонада носа", .ecgMonitor: "ЭКГ, монитор", .injections: "Инъекции", .inhalation: "Ингаляция O₂", .troponin: "БСЖК, тропонин", .glucoseMonitoring: "Глюкометрия", .masks: "Маски", .gloves: "Перчатки", .napkins: "Салфетки", .syringe: "Шприц", .siz: "СИЗ", .catheterPerefirichesky: "Катетер периферический", .binty: "Бинты", .glukometrya: "Глюкометрия", .infusionSystem: "Инфузионная система",
    ]
    
    static  let frames: [SubAttribute: [FrameOfSubAttribute]] = [
        .Complaints: [FrameOfSubAttribute(x: 50, y: 43, weight: 500, height: 30, paragraphLenght: 10, lineSpacing: 3, isMain: true)],
        .gotSickBeforeAnHour: [FrameOfSubAttribute(x: 77, y: 75.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .gotSick1_3Hours:  [FrameOfSubAttribute(x: 113, y: 75.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .gotSick3_6Hours:  [FrameOfSubAttribute(x: 152.5, y: 75.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .gotSick6_12Hours:  [FrameOfSubAttribute(x: 192.3, y: 75.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .gotSickMoreADay: [FrameOfSubAttribute(x: 235.4, y: 75.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .anamnesis: [FrameOfSubAttribute(x: 48, y: 86.5, weight: 500, height: 51, paragraphLenght: 34, lineSpacing: 1.55, isMain: true)],
        .allergologicalAnamnesis: [FrameOfSubAttribute(x: 48, y: 137.5, weight: 500, height: 30, paragraphLenght: 66, lineSpacing: 1.42, isMain: true)],
        .conditionIsSatisfactory: [FrameOfSubAttribute(x: 179, y: 170.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .conditionIsOfModerateSeverity: [FrameOfSubAttribute(x: 254, y: 170.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .conditionIsHeavy: [FrameOfSubAttribute(x: 318, y: 170.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .conditionIsTerminal: [FrameOfSubAttribute(x: 356, y: 170.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .conditionIsDeath: [FrameOfSubAttribute(x: 412, y: 170.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .consciousnessIsClear: [FrameOfSubAttribute(x: 81, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .consciousnessIsStunning: [FrameOfSubAttribute(x: 110, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .consciousnessIsSopor: [FrameOfSubAttribute(x: 157, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .consciousnessIsComa1: [FrameOfSubAttribute(x: 212.5, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 185, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .consciousnessIsComa2: [FrameOfSubAttribute(x: 227.5, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 185, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .consciousnessIsComa3: [FrameOfSubAttribute(x: 244, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 185, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .shkg: [FrameOfSubAttribute(x: 265, y: 183, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: false), FrameOfSubAttribute(x: 289, y: 183, weight: 22, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positionIsActive: [FrameOfSubAttribute(x: 379, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positionIsPassive: [FrameOfSubAttribute(x: 420, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positionIsForced: [FrameOfSubAttribute(x: 464, y: 182.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positionText: [FrameOfSubAttribute(x: 513, y: 182.5, weight: 33, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsDry: [FrameOfSubAttribute(x: 103, y: 194.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsWet: [FrameOfSubAttribute(x: 137, y: 194.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsWarm: [FrameOfSubAttribute(x: 180.5, y: 194.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsCold: [FrameOfSubAttribute(x: 218, y: 194.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsPhisiologicalColor: [FrameOfSubAttribute(x: 265.5, y: 194.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsPale: [FrameOfSubAttribute(x: 361.5, y: 194.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsHyperemic: [FrameOfSubAttribute(x: 403.7, y: 194.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsCyanotic: [FrameOfSubAttribute(x: 477.5, y: 194.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsJaundice: [FrameOfSubAttribute(x: 47, y: 205.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsAcrocyanosis: [FrameOfSubAttribute(x: 97, y: 205.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .skinIsMarbling: [FrameOfSubAttribute(x: 148.5, y: 205.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .lymphonoduses: [FrameOfSubAttribute(x: 241, y: 206, weight: 98, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNotRash: [FrameOfSubAttribute(x: 365, y: 205.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasRash: [FrameOfSubAttribute(x: 389, y: 205.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .rashText: [FrameOfSubAttribute(x: 410, y: 206, weight: 137, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .visibleMucous: [FrameOfSubAttribute(x: 113, y: 219.5, weight: 111, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNotEdema: [FrameOfSubAttribute(x: 249.5, y: 218.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasEdema: [FrameOfSubAttribute(x: 275, y: 218.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .edemaText: [FrameOfSubAttribute(x: 298, y: 219.5, weight: 104, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .turgorOfTissue: [FrameOfSubAttribute(x: 448, y: 219.5, weight: 100, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .behaviorIsCalm: [FrameOfSubAttribute(x: 143.5, y: 230.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .behaviorIsAgitated: [FrameOfSubAttribute(x: 191, y: 230.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .behaviorIsAggressive: [FrameOfSubAttribute(x: 248.5, y: 230.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .behaviorIsDepressive: [FrameOfSubAttribute(x: 300.5, y: 230.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .behaviorIsKontacten: [FrameOfSubAttribute(x: 359.5, y: 230.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .behaviorIsNotKontacten: [FrameOfSubAttribute(x: 405, y: 230.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .behaviorIsAmnesia: [FrameOfSubAttribute(x: 458, y: 230.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .behaviorIsataxia: [FrameOfSubAttribute(x: 499, y: 230.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .speech: [FrameOfSubAttribute(x: 64, y: 243, weight: 47, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pupilsIsODIsEqualOS: [FrameOfSubAttribute(x: 141, y: 242.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pupilsIsODIsNotEqualOS: [FrameOfSubAttribute(x: 180, y: 242.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pupilsIsNormal: [FrameOfSubAttribute(x: 220.5, y: 242.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pupilsIsWide: [FrameOfSubAttribute(x: 263.5, y: 242.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pupilsIsNarrow: [FrameOfSubAttribute(x: 304, y: 242.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pupilsIsAnisocoria: [FrameOfSubAttribute(x: 334, y: 242.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .reactionToLightIsAlive: [FrameOfSubAttribute(x: 439, y: 242.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .reactionToLightIsHoly: [FrameOfSubAttribute(x: 471, y: 242.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .reactionToLightIsNone: [FrameOfSubAttribute(x: 504.5, y: 242.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNotNystagm: [FrameOfSubAttribute(x: 76, y: 255.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNystagm: [FrameOfSubAttribute(x: 103, y: 255.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .nystagmText: [FrameOfSubAttribute(x: 127.5, y: 255.5, weight: 53, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNotMeningealSymptom: [FrameOfSubAttribute(x: 274.5, y: 255.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .regedivnostZatilochnihMuscle: [FrameOfSubAttribute(x: 298, y: 255.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 327, y: 255.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .kernig: [FrameOfSubAttribute(x: 298, y: 255.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 436, y: 255.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .brudzinski: [FrameOfSubAttribute(x: 298, y: 255.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 474, y: 255.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasFocalSymptoms: [FrameOfSubAttribute(x: 141, y: 266.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNotFocalSymptoms: [FrameOfSubAttribute(x: 116, y: 266.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .focalSymptomsText: [FrameOfSubAttribute(x: 167, y: 266.5, weight: 378, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .breathFeel: [FrameOfSubAttribute(x: 173, y: 279.5, weight: 74, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .breathNotFeel: [FrameOfSubAttribute(x: 173, y: 279.5, weight: 74, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNotSeparatedFromNasalPassages: [FrameOfSubAttribute(x: 351, y: 279, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasSeparatedFromNasalPassages: [FrameOfSubAttribute(x: 376, y: 279, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pharynx: [FrameOfSubAttribute(x: 413, y: 279.5, weight: 132, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .tonsils: [FrameOfSubAttribute(x: 72, y: 291.5, weight: 80, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .chdd: [FrameOfSubAttribute(x: 158, y: 291.5, weight: 16, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .dyspneaIsInspiratory: [FrameOfSubAttribute(x: 229.5, y: 291.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .dyspneaIsExpiratory: [FrameOfSubAttribute(x: 292, y: 291.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .dyspneaIsmixed: [FrameOfSubAttribute(x: 352.5, y: 291.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .dyspneaIsPotalogic: [FrameOfSubAttribute(x: 403.5, y: 291.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .percussionSoundIsPulmonary: [FrameOfSubAttribute(x: 108, y: 302.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .percussionSoundIsShortened: [FrameOfSubAttribute(x: 150.5, y: 302.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .percussionSoundIsTympanic: [FrameOfSubAttribute(x: 192, y: 302.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .percussionSoundIsDull: [FrameOfSubAttribute(x: 256.5, y: 302.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .percussionSoundIsBoxboardAbove: [FrameOfSubAttribute(x: 289, y: 302.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .percussionSoundText: [FrameOfSubAttribute(x: 350, y: 303.5, weight: 64, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .auscultationBreathIsPuerile: [FrameOfSubAttribute(x: 504, y: 302.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .auscultationBreathIsVesicular: [FrameOfSubAttribute(x: 47, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .auscultationBreathIsBronchial: [FrameOfSubAttribute(x: 102.5, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .auscultationBreathIsHard: [FrameOfSubAttribute(x: 158.5, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .auscultationBreathIsTenatic: [FrameOfSubAttribute(x: 196.5, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .auscultationBreathIsWeakened: [FrameOfSubAttribute(x: 257, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .auscultationBreathNone: [FrameOfSubAttribute(x: 305, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .auscultationBreathText: [FrameOfSubAttribute(x: 349, y: 315, weight: 63, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNotRale: [FrameOfSubAttribute(x: 440, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .dryRale: [FrameOfSubAttribute(x: 484.5, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 462, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .wetRaleSmallbubble: [FrameOfSubAttribute(x: 514, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 462, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 46.5 , y: 326.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .wetRaleMediumbubble: [FrameOfSubAttribute(x: 514, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 462, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true), FrameOfSubAttribute(x: 80.5, y: 326.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .wetRaleLargebubble: [FrameOfSubAttribute(x: 514, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true),FrameOfSubAttribute(x: 462, y: 315, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true),
                              FrameOfSubAttribute(x: 118.5, y: 326.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .raleText: [FrameOfSubAttribute(x: 195, y: 327.5, weight: 72, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNotPleuralFrictionNoise: [FrameOfSubAttribute(x: 341, y: 326.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasPleuralFrictionNoise: [FrameOfSubAttribute(x: 366, y: 326.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .cough: [FrameOfSubAttribute(x: 445, y: 327.5, weight: 96, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .heartContractions: [FrameOfSubAttribute(x: 206, y: 339.5, weight: 174, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .heartTonesIsResonant: [FrameOfSubAttribute(x: 429.5, y: 338.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .heartTonesIsPriglasheny: [FrameOfSubAttribute(x: 469, y: 338.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .heartTonesIsDeaf: [FrameOfSubAttribute(x: 520.5, y: 338.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .noiseIsSystolic: [FrameOfSubAttribute(x: 64, y: 351.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .noiseIsDiastolic: [FrameOfSubAttribute(x: 129, y: 351.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .noiseIsAccent: [FrameOfSubAttribute(x: 197, y: 351.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .noiseText: [FrameOfSubAttribute(x: 228, y: 352, weight: 60, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pulse: [FrameOfSubAttribute(x: 312, y: 352, weight: 52, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .deficit: [FrameOfSubAttribute(x: 422, y: 352, weight: 122, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNotNoiseOfFrictionPericard: [FrameOfSubAttribute(x: 121.5, y: 362.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hasNoiseOfFrictionPericard: [FrameOfSubAttribute(x: 144, y: 362.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .normalAD: [FrameOfSubAttribute(x: 218, y: 363, weight: 138, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .maxAD: [FrameOfSubAttribute(x: 391, y: 363, weight: 152, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .tongueIsWet: [FrameOfSubAttribute(x: 137.5, y: 374.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .tongueIsDry: [FrameOfSubAttribute(x: 177.5, y: 374.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .tongueIsOverlaid: [FrameOfSubAttribute(x: 208, y: 374.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .tongueText: [FrameOfSubAttribute(x: 246, y: 375, weight: 71, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .stomachShape: [FrameOfSubAttribute(x: 367, y: 375, weight: 78, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .stomachIsSoft: [FrameOfSubAttribute(x: 451, y: 374.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .stomachIsTense: [FrameOfSubAttribute(x: 485, y: 374.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .stomachIsPainful: [FrameOfSubAttribute(x: 46.5, y: 386.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .stomachIsNotPainful: [FrameOfSubAttribute(x: 99, y: 387, weight: 122, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .stomachText: [FrameOfSubAttribute(x: 103, y: 387, weight: 116, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfSidkovskogo: [FrameOfSubAttribute(x: 314, y: 386.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomRovsinga: [FrameOfSubAttribute(x: 365, y: 386.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomMerphy: [FrameOfSubAttribute(x: 406, y: 386.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfOrtner: [FrameOfSubAttribute(x: 443.5, y: 386.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfMayoRobson: [FrameOfSubAttribute(x: 483, y: 386.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfObraztsov: [FrameOfSubAttribute(x: 46.5, y: 399.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfRazdolsky: [FrameOfSubAttribute(x: 94.5, y: 399.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfShchetkinBlumberg: [FrameOfSubAttribute(x: 149.5, y: 399.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfValya: [FrameOfSubAttribute(x: 227, y: 399.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfSklyarov: [FrameOfSubAttribute(x: 256, y: 399.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfGrekov: [FrameOfSubAttribute(x: 299, y: 399.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfRozanov: [FrameOfSubAttribute(x: 339, y: 399.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .positiveSymptomOfSpijarski: [FrameOfSubAttribute(x: 381.5, y: 399.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .liver: [FrameOfSubAttribute(x: 71, y: 411, weight: 142, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .hepaticDullness: [FrameOfSubAttribute(x: 280, y: 411, weight: 95, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .spleen: [FrameOfSubAttribute(x: 411, y: 411, weight: 133, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .dyspepsiaNausea: [FrameOfSubAttribute(x: 84, y: 422.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .dyspepsiaVomiting: [FrameOfSubAttribute(x: 123, y: 422.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .dyspepsiaText: [FrameOfSubAttribute(x: 152, y: 422.5, weight: 43, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .chairIsFormed: [FrameOfSubAttribute(x: 246, y: 422.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .chairIsZapor: [FrameOfSubAttribute(x: 304, y: 422.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .chairIsLiquid: [FrameOfSubAttribute(x: 333.5, y: 422.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .chairText: [FrameOfSubAttribute(x: 365, y: 423, weight: 132, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .chairPeriodicity: [FrameOfSubAttribute(x: 526, y: 423, weight: 19, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .kidneys: [FrameOfSubAttribute(x: 166, y: 434.5, weight: 154, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .smPounding: [FrameOfSubAttribute(x: 387, y: 434.5, weight: 163, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .diuresisIsSufficient: [FrameOfSubAttribute(x: 72.5, y: 446.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .diuresisIsreduced: [FrameOfSubAttribute(x: 126, y: 446.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .diuresisIspolyuria: [FrameOfSubAttribute(x: 162.5, y: 446.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .diuresisIshematuria: [FrameOfSubAttribute(x: 204.5, y: 446.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .diuresisIsAnuria: [FrameOfSubAttribute(x: 251.5, y: 446.5, weight: 5, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .menses: [FrameOfSubAttribute(x: 396, y: 447, weight: 75, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .delay: [FrameOfSubAttribute(x: 507, y: 447, weight: 37, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .additionalData: [FrameOfSubAttribute(x: 48, y: 459, weight: 500, height: 51, paragraphLenght: 58, lineSpacing: 3.7, isMain: true)],
        .ecgBeforeMedicalCare: [FrameOfSubAttribute(x: 228, y: 508.5, weight: 317, height: 60, paragraphLenght: 44, lineSpacing: 2.4, isMain: true)],
        .ecgAfterMedicalCare: [FrameOfSubAttribute(x: 228, y: 564, weight: 317, height: 60, paragraphLenght: 23, lineSpacing: 2.5, isMain: true)],
        .assistanceProvided: [FrameOfSubAttribute(x: 258, y: 625, weight: 290, height: 136, paragraphLenght: 1, lineSpacing: 3.75, isMain: true)],
        .adBeforeMedHelp: [FrameOfSubAttribute(x: 96, y: 523, weight: 56, height: 31, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .adAfterMedHelp: [FrameOfSubAttribute(x: 154, y: 523, weight: 67, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .chssBeforeMedHelp: [FrameOfSubAttribute(x: 98, y: 535, weight: 56, height: 31, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .chssAfterMedHelp: [FrameOfSubAttribute(x: 154, y: 535, weight: 67, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pBeforeMedHelp: [FrameOfSubAttribute(x: 98, y: 546, weight: 56, height: 31, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        
        .pAfterMedHelp: [FrameOfSubAttribute(x: 154, y: 546, weight: 67, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .chddBeforeMedHelp: [FrameOfSubAttribute(x: 98, y: 558, weight: 56, height: 31, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .chddAfterMedHelp: [FrameOfSubAttribute(x: 154, y: 558, weight: 67, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .tBeforeMedHelp: [FrameOfSubAttribute(x: 98, y: 570, weight: 56, height: 31, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .tAfterMedHelp: [FrameOfSubAttribute(x: 154, y: 570, weight: 67, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .spOBeforeMedHelp: [FrameOfSubAttribute(x: 98, y: 581, weight: 56, height: 31, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .spOAfterMedHelp: [FrameOfSubAttribute(x: 154, y: 581, weight: 67, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .glukozaBeforeMedHelp: [FrameOfSubAttribute(x: 98, y: 594, weight: 56, height: 31, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .glukozaAfterMedHelp: [FrameOfSubAttribute(x: 154, y: 594, weight: 67, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .resuscitation: [FrameOfSubAttribute(x: 134, y: 611, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .ivl_vvl: [FrameOfSubAttribute(x: 134, y: 623, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .nebulizer: [FrameOfSubAttribute(x: 134, y: 636, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .intubationAndlaryngitis: [FrameOfSubAttribute(x: 134, y: 648, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .conicotomy: [FrameOfSubAttribute(x: 134, y: 660, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .trachestomy: [FrameOfSubAttribute(x: 134, y: 672, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .eit: [FrameOfSubAttribute(x: 134, y: 684, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .thrombolysis: [FrameOfSubAttribute(x: 134, y: 696, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .catheterMoch: [FrameOfSubAttribute(x: 134, y: 708, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pills: [FrameOfSubAttribute(x: 134, y: 721, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .rinsingStomach: [FrameOfSubAttribute(x: 134, y: 733, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .pulseoximetry: [FrameOfSubAttribute(x: 134, y: 746, weight: 18, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .infusion: [FrameOfSubAttribute(x: 236, y: 611, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .catheterVV: [FrameOfSubAttribute(x: 236, y: 623, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .ostBlodRan: [FrameOfSubAttribute(x: 236, y: 636, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .bandage: [FrameOfSubAttribute(x: 236, y: 648, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .immobilization: [FrameOfSubAttribute(x: 236, y: 660, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .defibrillation: [FrameOfSubAttribute(x: 236, y: 672, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .nasalTamponade: [FrameOfSubAttribute(x: 236, y: 684, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .ecgMonitor: [FrameOfSubAttribute(x: 236, y: 696, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .injections: [FrameOfSubAttribute(x: 236, y: 708, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .inhalation: [FrameOfSubAttribute(x: 236, y: 721, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .troponin: [FrameOfSubAttribute(x: 236, y: 733, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .glucoseMonitoring: [FrameOfSubAttribute(x: 236, y: 746, weight: 20, height: 13, paragraphLenght: 0, lineSpacing: 3, isMain: true)],
        .expenditure: [FrameOfSubAttribute(x: 48, y: 759.5, weight: 497, height: 28, paragraphLenght: 10, lineSpacing: 3, isMain: true)]
    ]
}
